chore: update all non-major updates (#1121)

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -3,27 +3,69 @@ on:
   pull_request:
 
 jobs:
-  e2e:
-    name: E2E result
+  playwright:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v5.0.0
-      - uses: taiga-family/ci/actions/setup/variables@v1.153.0
-      - uses: taiga-family/ci/actions/setup/node@v1.153.0
-      - uses: taiga-family/ci/actions/setup/playwright@v1.153.0
+      - uses: taiga-family/ci/actions/setup/variables@v1.194.0
+      - uses: taiga-family/ci/actions/setup/node@v1.194.0
+      - uses: taiga-family/ci/actions/setup/playwright@v1.194.0
       - run: npx nx e2e demo -- --update-snapshots
       - run: npx nx e2e demo
         continue-on-error: true
         env:
           BASE_URL: https://taiga-family.github.io/preview-landing-components/
 
-      - uses: taiga-family/ci/actions/setup/playwright-combine-failed-screenshot@v1.153.0
+      - uses: taiga-family/ci/actions/setup/playwright-combine-failed-screenshot@v1.194.0
         env:
           FAILED_SCREENSHOTS_PATH: apps/demo/e2e/tests-results
 
-      - uses: taiga-family/ci/actions/setup/playwright-diff-check@v1.153.0
+      - name: Upload artifacts / ${{ env.PLAYWRIGHT_SNAPSHOTS_ARTIFACTS_KEY }}
+        uses: actions/upload-artifact@v7.0.0
         with:
-          pw-result: apps/demo/e2e/tests-results
+          path: ./apps/demo/e2e/tests-results/**/*-retry2/**/*.diff.png
+          name: ${{ env.PLAYWRIGHT_SNAPSHOTS_ARTIFACTS_KEY }}
+          if-no-files-found: ignore
+          compression-level: 0
+          retention-days: 1
+
+  # workaround for status checks -- check this one job instead of each individual E2E job in the matrix
+  # see https://github.com/orgs/community/discussions/9141#discussioncomment-2296809
+  playwright-composite-result:
+    name: Playwright E2E Tests matrix result
+    if: ${{ always() }}
+    needs: [playwright]
+    runs-on: ubuntu-latest
+    steps:
+      - run: |
+          result="${{ needs.playwright.result }}"
+          # mark as successful even if skipped
+          if [[ $result == "success" || $result == "skipped" ]]; then
+            exit 0
+          else
+            exit 1
+          fi
+
+  result:
+    name: E2E result
+    needs: [playwright]
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v6.0.2
+      - uses: taiga-family/ci/actions/setup/variables@v1.194.0
+      - uses: taiga-family/ci/actions/setup/node@v1.194.0
+
+      - name: Download artifacts for Playwright
+        continue-on-error: true
+        uses: actions/download-artifact@v8.0.1
+        with:
+          path: ./total/playwright
+          pattern: playwright-snapshots-artifacts--*
+          merge-multiple: true
+      - run: ls -R ./total/playwright || echo "not found"
+      - uses: taiga-family/ci/actions/setup/playwright-diff-check@v1.194.0
+        with:
+          pw-result: ./total/playwright
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
